### ISSUE TITLE
What happens when ECB website is down?

### ISSUE THREAD

**Issue by ptahchiev** [JavaMoney/jsr354-ri#176]
Hello,
i'm visiting a client in Ukraine. Now I try to show them a demo of my shop running locally and amazingly the product-details page does not load. Firefox just loads the page forever. **30 minutes later** I get this exception in the log:
````
2017-11-20 18:05:30,930 org.javamoney.moneta.internal.loader.LoadableResource [https-jsse-nio-127.0.0.1-8112-exec-4] INFO : Failed to load resource input for ECBHistoric90RateProvider from http://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist-90d.xml
java.net.SocketException: Connection timed out (Read failed)
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:706)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at org.javamoney.moneta.internal.loader.LoadableResource.load(LoadableResource.java:319)
	at org.javamoney.moneta.internal.loader.LoadableResource.loadRemote(LoadableResource.java:230)
	at org.javamoney.moneta.internal.loader.LoadRemoteDataLoaderService.execute(LoadRemoteDataLoaderService.java:41)
	at org.javamoney.moneta.internal.loader.DefaultLoaderServiceFacade.loadDataRemote(DefaultLoaderServiceFacade.java:51)
	at org.javamoney.moneta.internal.loader.DefaultLoaderService.registerData(DefaultLoaderService.java:163)
	at org.javamoney.moneta.internal.loader.LoaderConfigurator.initResource(LoaderConfigurator.java:92)
	at org.javamoney.moneta.internal.loader.LoaderConfigurator.load(LoaderConfigurator.java:59)
	at org.javamoney.moneta.internal.loader.DefaultLoaderService.initialize(DefaultLoaderService.java:99)
	at org.javamoney.moneta.internal.loader.DefaultLoaderService.<init>(DefaultLoaderService.java:83)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.javamoney.moneta.internal.PriorityAwareServiceProvider.loadServices(PriorityAwareServiceProvider.java:98)
	at org.javamoney.moneta.internal.PriorityAwareServiceProvider.getServices(PriorityAwareServiceProvider.java:65)
````

So it seems like it cannot load the xml file with the exchange rates. So I ask my colleagues in Bulgaria if they can open this URL http://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist-90d.xml and they say: "Yes, it downloads an xml file". I try to open it from Kiev in my browser and, again, firefox keeps loading forever and after 30 minutes tells me it cannot load the page. Meanwhile the ECB website http://www.ecb.europa.eu/home/html/index.en.html loads perfectly fine. So it's only the XML resource that cannot be downloaded for some reason!
My questions here:
 - is there anywhere where I can configure a timeout?
 - what would happen if one exchange rate provider does not fail, but instead takes forever to answer your call (like in my case).
 - is it possible the ECB or IMF blacklist me or my machines because I've been downloading too many times the XML echange rate file?

**Comment by keilw** [comment]
In the Ukraine, Russia, Turkey, Middle East, China, etc. who knows, there could also be some state-imposed firewalls or trying to protect from hostile (Russian in your case) hackers. Especially from countries like the Ukraine, Russia, Baltics, etc. which are often both victim and sources of large scale hacking, malware, and similar online mess, it is not unlikely the ECB or IMF have some blocks in place to avoid being hacked or say exchange rates altered for the gain of mobsters and their friends (all the way into the White House or US administration itself ;-/ )

**Comment by Koziolek** [comment]
hi!

Check your client firewall configuration (just manually download file). In many companies in eastern Europe admins and security officers has some kind of paranoia (if know what i mean) and block everything. In addition check that from other connection like hotel WiFi.

**Comment by ptahchiev** [comment]
OK, 
like I said this loads perfectly fine:

http://www.ecb.europa.eu/home/html/index.en.html 

and this times out after 30 minutes:

http://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist-90d.xml 

I don't think it's firewall issue. And even if it is, my question is still valid. How can I configure the timeout to be 10 seconds for example?

**Comment by atsticks** [comment]
We will add
```
connection.connect.timeout
connection.read.timeout
```
as properties (in seconds) setting them to 10 seconds by default in the next release.
