### ISSUE TITLE
Missing `uses`

### ISSUE THREAD

**Issue by ldesgrange** [JavaMoney/jsr354-ri#219]
Hi,

I'm new with Java modules, so I may be missing something, but when trying to use moneta I always get a stacktrace like this:

```
Exception in thread "main" java.util.ServiceConfigurationError: javax.money.spi.MonetaryCurrenciesSingletonSpi: module org.javamoney.moneta does not declare `uses`
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:588)
	at java.base/java.util.ServiceLoader.checkCaller(ServiceLoader.java:574)
	at java.base/java.util.ServiceLoader.<init>(ServiceLoader.java:503)
	at java.base/java.util.ServiceLoader.load(ServiceLoader.java:1684)
	at org.javamoney.moneta/org.javamoney.moneta.internal.PriorityAwareServiceProvider.loadServices(PriorityAwareServiceProvider.java:98)
	at org.javamoney.moneta/org.javamoney.moneta.internal.PriorityAwareServiceProvider.getServices(PriorityAwareServiceProvider.java:65)
	at java.money/javax.money.spi.Bootstrap.getService(Bootstrap.java:113)
	at java.money/javax.money.Monetary.MONETARY_CURRENCIES_SINGLETON_SPI(Monetary.java:42)
	at java.money/javax.money.Monetary.getCurrency(Monetary.java:382)
```

Here is a simple example:

- `src/main/java/module-info.java`
```java
module demo {
    requires org.javamoney.moneta;
}
```
- `src/main/java/demo/Application.java`
```java
package demo;
import javax.money.Monetary;
public class Application {
    public static void main(String[] args) {
        System.out.println("USD: " + Monetary.getCurrency("USD"));
    }
}
```
- `build.gradle`
```gradle
plugins {
    id 'application'
    id 'org.gradle.java.experimental-jigsaw' version '0.1.1'
}
javaModule.name = 'demo'
mainClassName = 'demo.Application'
sourceCompatibility = 9
targetCompatibility = 9
repositories {
    mavenCentral()
}
dependencies {
    implementation 'org.javamoney.moneta:moneta-core:1.3'
}
```

Using gradle (`./gradlew run`) or compiling the module, creating the jar and running it by hand (javac, jar, java…) gives me the same stacktrace (with java 9.0.4 and 10.0.2).

Adding the following to `moneta-core/src/main/java/org/javamoney/moneta/module-info.java` solved the issue:
```
    uses javax.money.spi.MonetaryCurrenciesSingletonSpi;
    uses javax.money.spi.CurrencyProviderSpi;
```

Am I doing something wrong or is there some `uses` missing from `moneta-core`?

**Comment by marschall** [comment]
As the call is coming from `javax.money.spi.Bootstrap` I believe the bug is in the RI.
